# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Obtain residuals with Rcpp
#' 
#' For given AR, bwd MA, fwd MA parameters, calculate the residuals (B and Sigma are taken into account later).
#' The input arguments \code{polm_ar}, \code{polm_ma_fwd}, \code{polm_ma_bwd} are in a different format than usual for this Rcpp function, 
#' i.e. they are in wide matrices.
#' Also note that \eqn{p_0} is not necessarily the identity matrix and needs to be inverted in the code below.
#' \cr
#' What is happening in this function is better documented in its R version: \link{get_residuals_R}
#'
#' @param data_in const arma::mat reference. Observations correspond to columns.
#' @param polm_ar,polm_ma_fwd const arma::mat references. Wide matrices.
#'   \eqn{I_n, a_1, \ldots, a_p} and \eqn{f_1, \ldots, f_K}
#' @param polm_ma_bwd arma::mat reference. 
#'   \strong{NOT CONST} because \eqn{p_0} needs to be inverted, 
#'   applied to \eqn{p_q, \ldots, p_1, p_0}, and then the new \eqn{p_0 = I_n} needs to be discarded
#' @param kappa,k const arma::uword references. Partial indices
#' 
#' @return Object of type arma::mat. Wide data matrix (rows correspond to variables, observations to columns) of residuals.
#'
#' @export
get_residuals <- function(data_in, polm_ar, polm_ma_bwd, polm_ma_fwd, kappa, k) {
    .Call(`_svarmawhf_get_residuals`, data_in, polm_ar, polm_ma_bwd, polm_ma_fwd, kappa, k)
}

#' Rcpp version of solve_ARMA
#'
#' @param a,b Parameter matrices. Check R version for details.
#' @param u,y Data. y is overwritten, u is const reference. 
#' @param t0 Integer specifying at what index iteration should be started.
#' 
#' @return void
#'
#' @export
#' @name solve_ARMA
#' @keywords internal
solve_ARMA_cpp <- function(a, b, u, y, t0) {
    invisible(.Call(`_svarmawhf_solve_ARMA_cpp`, a, b, u, y, t0))
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_svarmawhf_RcppExport_registerCCallable', PACKAGE = 'svarmawhf')
})
